# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_heladeria.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaHeladeria(object):
    def setupUi(self, ventanaHeladeria):
        ventanaHeladeria.setObjectName("ventanaHeladeria")
        ventanaHeladeria.resize(814, 562)
        self.grupo_helados = QtWidgets.QGroupBox(ventanaHeladeria)
        self.grupo_helados.setGeometry(QtCore.QRect(30, 200, 281, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grupo_helados.setFont(font)
        self.grupo_helados.setFlat(False)
        self.grupo_helados.setCheckable(True)
        self.grupo_helados.setChecked(True)
        self.grupo_helados.setObjectName("grupo_helados")
        self.check_turron = QtWidgets.QCheckBox(self.grupo_helados)
        self.check_turron.setGeometry(QtCore.QRect(30, 50, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_turron.setFont(font)
        self.check_turron.setObjectName("check_turron")
        self.check_muerte = QtWidgets.QCheckBox(self.grupo_helados)
        self.check_muerte.setGeometry(QtCore.QRect(30, 90, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_muerte.setFont(font)
        self.check_muerte.setObjectName("check_muerte")
        self.check_after = QtWidgets.QCheckBox(self.grupo_helados)
        self.check_after.setGeometry(QtCore.QRect(30, 130, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_after.setFont(font)
        self.check_after.setObjectName("check_after")
        self.check_dama = QtWidgets.QCheckBox(self.grupo_helados)
        self.check_dama.setGeometry(QtCore.QRect(30, 170, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_dama.setFont(font)
        self.check_dama.setObjectName("check_dama")
        self.etq_heladeria = QtWidgets.QLabel(ventanaHeladeria)
        self.etq_heladeria.setGeometry(QtCore.QRect(230, 10, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.etq_heladeria.setFont(font)
        self.etq_heladeria.setFrameShape(QtWidgets.QFrame.Panel)
        self.etq_heladeria.setFrameShadow(QtWidgets.QFrame.Raised)
        self.etq_heladeria.setObjectName("etq_heladeria")
        self.etq_helado = QtWidgets.QLabel(ventanaHeladeria)
        self.etq_helado.setGeometry(QtCore.QRect(40, 130, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.etq_helado.setFont(font)
        self.etq_helado.setObjectName("etq_helado")
        self.etq_bebida = QtWidgets.QLabel(ventanaHeladeria)
        self.etq_bebida.setGeometry(QtCore.QRect(440, 130, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.etq_bebida.setFont(font)
        self.etq_bebida.setObjectName("etq_bebida")
        self.grupo_bebidas = QtWidgets.QGroupBox(ventanaHeladeria)
        self.grupo_bebidas.setGeometry(QtCore.QRect(440, 200, 331, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grupo_bebidas.setFont(font)
        self.grupo_bebidas.setCheckable(True)
        self.grupo_bebidas.setObjectName("grupo_bebidas")
        self.check_zumo = QtWidgets.QCheckBox(self.grupo_bebidas)
        self.check_zumo.setGeometry(QtCore.QRect(20, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_zumo.setFont(font)
        self.check_zumo.setObjectName("check_zumo")
        self.check_smoothie = QtWidgets.QCheckBox(self.grupo_bebidas)
        self.check_smoothie.setGeometry(QtCore.QRect(20, 90, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_smoothie.setFont(font)
        self.check_smoothie.setObjectName("check_smoothie")
        self.check_chocolate = QtWidgets.QCheckBox(self.grupo_bebidas)
        self.check_chocolate.setGeometry(QtCore.QRect(20, 130, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_chocolate.setFont(font)
        self.check_chocolate.setObjectName("check_chocolate")
        self.check_cafe = QtWidgets.QCheckBox(self.grupo_bebidas)
        self.check_cafe.setGeometry(QtCore.QRect(20, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.check_cafe.setFont(font)
        self.check_cafe.setObjectName("check_cafe")
        self.etq_imp = QtWidgets.QLabel(ventanaHeladeria)
        self.etq_imp.setGeometry(QtCore.QRect(40, 480, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.etq_imp.setFont(font)
        self.etq_imp.setObjectName("etq_imp")
        self.etq_importe = QtWidgets.QLabel(ventanaHeladeria)
        self.etq_importe.setGeometry(QtCore.QRect(320, 470, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.etq_importe.setFont(font)
        self.etq_importe.setFrameShape(QtWidgets.QFrame.Panel)
        self.etq_importe.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.etq_importe.setObjectName("etq_importe")
        self.separador3 = QtWidgets.QFrame(ventanaHeladeria)
        self.separador3.setGeometry(QtCore.QRect(440, 490, 371, 20))
        self.separador3.setFrameShape(QtWidgets.QFrame.HLine)
        self.separador3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separador3.setObjectName("separador3")
        self.separador1 = QtWidgets.QFrame(ventanaHeladeria)
        self.separador1.setGeometry(QtCore.QRect(360, 80, 41, 391))
        self.separador1.setFrameShape(QtWidgets.QFrame.VLine)
        self.separador1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separador1.setObjectName("separador1")
        self.separador2 = QtWidgets.QFrame(ventanaHeladeria)
        self.separador2.setGeometry(QtCore.QRect(200, 500, 118, 3))
        self.separador2.setFrameShape(QtWidgets.QFrame.HLine)
        self.separador2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separador2.setObjectName("separador2")

        self.retranslateUi(ventanaHeladeria)
        QtCore.QMetaObject.connectSlotsByName(ventanaHeladeria)

    def retranslateUi(self, ventanaHeladeria):
        _translate = QtCore.QCoreApplication.translate
        ventanaHeladeria.setWindowTitle(_translate("ventanaHeladeria", "Heladería"))
        self.grupo_helados.setTitle(_translate("ventanaHeladeria", "   Helados:     "))
        self.check_turron.setText(_translate("ventanaHeladeria", "Copa Turrón - 5.80 €"))
        self.check_muerte.setText(_translate("ventanaHeladeria", "Muerte por chocolate - 5.10 €"))
        self.check_after.setText(_translate("ventanaHeladeria", "Copa AfterEight - 5.10 €"))
        self.check_dama.setText(_translate("ventanaHeladeria", "Dama blanca - 5.20 €"))
        self.etq_heladeria.setText(_translate("ventanaHeladeria", "     Heladería Del \'Ice"))
        self.etq_helado.setText(_translate("ventanaHeladeria", "Escoge tu helado: "))
        self.etq_bebida.setText(_translate("ventanaHeladeria", "Escoge tu bebida:"))
        self.grupo_bebidas.setTitle(_translate("ventanaHeladeria", "  Bebidas:  "))
        self.check_zumo.setText(_translate("ventanaHeladeria", "Zumo de naranja - 1.80 €"))
        self.check_smoothie.setText(_translate("ventanaHeladeria", "Smoothie - 3.50 € "))
        self.check_chocolate.setText(_translate("ventanaHeladeria", "Chocolate caliente - 1.80 € "))
        self.check_cafe.setText(_translate("ventanaHeladeria", "Café - 1.10 €"))
        self.etq_imp.setText(_translate("ventanaHeladeria", "Importe Total: "))
        self.etq_importe.setText(_translate("ventanaHeladeria", "0 €"))
