# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_pizzeria.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaDialogo(object):
    def setupUi(self, ventanaDialogo):
        ventanaDialogo.setObjectName("ventanaDialogo")
        ventanaDialogo.resize(808, 613)
        font = QtGui.QFont()
        font.setPointSize(12)
        ventanaDialogo.setFont(font)
        self.etq_precio = QtWidgets.QLabel(ventanaDialogo)
        self.etq_precio.setGeometry(QtCore.QRect(30, 130, 581, 41))
        self.etq_precio.setObjectName("etq_precio")
        self.etq_precio_final = QtWidgets.QLabel(ventanaDialogo)
        self.etq_precio_final.setGeometry(QtCore.QRect(620, 130, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.etq_precio_final.setFont(font)
        self.etq_precio_final.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.etq_precio_final.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.etq_precio_final.setObjectName("etq_precio_final")
        self.separador1 = QtWidgets.QFrame(ventanaDialogo)
        self.separador1.setGeometry(QtCore.QRect(20, 190, 761, 20))
        self.separador1.setFrameShape(QtWidgets.QFrame.HLine)
        self.separador1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separador1.setObjectName("separador1")
        self.etq_complementos = QtWidgets.QLabel(ventanaDialogo)
        self.etq_complementos.setGeometry(QtCore.QRect(30, 230, 231, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.etq_complementos.setFont(font)
        self.etq_complementos.setObjectName("etq_complementos")
        self.etq_titulo = QtWidgets.QLabel(ventanaDialogo)
        self.etq_titulo.setGeometry(QtCore.QRect(160, 30, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.etq_titulo.setFont(font)
        self.etq_titulo.setFrameShape(QtWidgets.QFrame.Panel)
        self.etq_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.etq_titulo.setObjectName("etq_titulo")
        self.gridLayoutWidget = QtWidgets.QWidget(ventanaDialogo)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 300, 741, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.check_champis = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_champis.setObjectName("check_champis")
        self.gridLayout.addWidget(self.check_champis, 1, 1, 1, 1)
        self.check_pollo = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_pollo.setObjectName("check_pollo")
        self.gridLayout.addWidget(self.check_pollo, 2, 1, 1, 1)
        self.check_aceitunas = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_aceitunas.setObjectName("check_aceitunas")
        self.gridLayout.addWidget(self.check_aceitunas, 0, 1, 1, 1)
        self.check_pepperoni = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_pepperoni.setObjectName("check_pepperoni")
        self.gridLayout.addWidget(self.check_pepperoni, 2, 0, 1, 1)
        self.check_atun = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_atun.setObjectName("check_atun")
        self.gridLayout.addWidget(self.check_atun, 0, 0, 1, 1)
        self.check_cebolla = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_cebolla.setObjectName("check_cebolla")
        self.gridLayout.addWidget(self.check_cebolla, 1, 0, 1, 1)
        self.check_bacon = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_bacon.setObjectName("check_bacon")
        self.gridLayout.addWidget(self.check_bacon, 0, 2, 1, 1)
        self.check_jamon = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_jamon.setObjectName("check_jamon")
        self.gridLayout.addWidget(self.check_jamon, 1, 2, 1, 1)
        self.check_york = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_york.setObjectName("check_york")
        self.gridLayout.addWidget(self.check_york, 2, 2, 1, 1)

        self.retranslateUi(ventanaDialogo)
        QtCore.QMetaObject.connectSlotsByName(ventanaDialogo)

    def retranslateUi(self, ventanaDialogo):
        _translate = QtCore.QCoreApplication.translate
        ventanaDialogo.setWindowTitle(_translate("ventanaDialogo", "Pizzeria"))
        self.etq_precio.setText(_translate("ventanaDialogo", "Precio de la pizza mediana  (base +  salsa de tomate + queso 100% mozarella): "))
        self.etq_precio_final.setText(_translate("ventanaDialogo", "12.20  €"))
        self.etq_complementos.setText(_translate("ventanaDialogo", "Complementos (+1,95 €) : "))
        self.etq_titulo.setText(_translate("ventanaDialogo", "            PIZZERIA VERONA"))
        self.check_champis.setText(_translate("ventanaDialogo", "Champiñones"))
        self.check_pollo.setText(_translate("ventanaDialogo", "Pollo a la parrilla"))
        self.check_aceitunas.setText(_translate("ventanaDialogo", "Aceitunas negras"))
        self.check_pepperoni.setText(_translate("ventanaDialogo", "Pepperoni"))
        self.check_atun.setText(_translate("ventanaDialogo", "Atún"))
        self.check_cebolla.setText(_translate("ventanaDialogo", "Cebolla"))
        self.check_bacon.setText(_translate("ventanaDialogo", "Bacon"))
        self.check_jamon.setText(_translate("ventanaDialogo", "Jamón serrano"))
        self.check_york.setText(_translate("ventanaDialogo", "York"))
