# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_alta.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaRegistro(object):
    def setupUi(self, ventanaRegistro):
        ventanaRegistro.setObjectName("ventanaRegistro")
        ventanaRegistro.resize(1300, 900)
        font = QtGui.QFont()
        font.setPointSize(12)
        ventanaRegistro.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ventanaRegistro)
        self.centralwidget.setObjectName("centralwidget")
        self.etq_titulo = QtWidgets.QLabel(self.centralwidget)
        self.etq_titulo.setGeometry(QtCore.QRect(520, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.etq_titulo.setFont(font)
        self.etq_titulo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.etq_titulo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.etq_titulo.setObjectName("etq_titulo")
        self.etq_referencia = QtWidgets.QLabel(self.centralwidget)
        self.etq_referencia.setGeometry(QtCore.QRect(40, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_referencia.setFont(font)
        self.etq_referencia.setObjectName("etq_referencia")
        self.line_referencia = QtWidgets.QLineEdit(self.centralwidget)
        self.line_referencia.setGeometry(QtCore.QRect(160, 100, 191, 31))
        self.line_referencia.setObjectName("line_referencia")
        self.etq_nombre = QtWidgets.QLabel(self.centralwidget)
        self.etq_nombre.setGeometry(QtCore.QRect(620, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_nombre.setFont(font)
        self.etq_nombre.setObjectName("etq_nombre")
        self.line_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nombre.setGeometry(QtCore.QRect(710, 100, 521, 31))
        self.line_nombre.setObjectName("line_nombre")
        self.etq_tipo = QtWidgets.QLabel(self.centralwidget)
        self.etq_tipo.setGeometry(QtCore.QRect(40, 175, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_tipo.setFont(font)
        self.etq_tipo.setObjectName("etq_tipo")
        self.combo_tipo = QtWidgets.QComboBox(self.centralwidget)
        self.combo_tipo.setGeometry(QtCore.QRect(160, 170, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_tipo.setFont(font)
        self.combo_tipo.setObjectName("combo_tipo")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.etq_escala = QtWidgets.QLabel(self.centralwidget)
        self.etq_escala.setGeometry(QtCore.QRect(620, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_escala.setFont(font)
        self.etq_escala.setObjectName("etq_escala")
        self.combo_escala = QtWidgets.QComboBox(self.centralwidget)
        self.combo_escala.setGeometry(QtCore.QRect(710, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_escala.setFont(font)
        self.combo_escala.setObjectName("combo_escala")
        self.combo_escala.addItem("")
        self.combo_escala.addItem("")
        self.combo_escala.addItem("")
        self.etq_fabricante = QtWidgets.QLabel(self.centralwidget)
        self.etq_fabricante.setGeometry(QtCore.QRect(40, 280, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_fabricante.setFont(font)
        self.etq_fabricante.setObjectName("etq_fabricante")
        self.combo_fabricante = QtWidgets.QComboBox(self.centralwidget)
        self.combo_fabricante.setGeometry(QtCore.QRect(160, 270, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_fabricante.setFont(font)
        self.combo_fabricante.setIconSize(QtCore.QSize(48, 48))
        self.combo_fabricante.setObjectName("combo_fabricante")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/aneste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/arnold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iconos/bachmann.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("iconos/brawa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("iconos/busch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("iconos/electrotren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("iconos/esu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("iconos/evergreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("iconos/faller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("iconos/fleischmann.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("iconos/grahamFarish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("iconos/hobbytrain.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("iconos/hornby.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("iconos/humbrol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon13, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("iconos/ibertren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon14, "")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("iconos/jouef.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("iconos/kato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon16, "")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("iconos/kibri.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon17, "")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("iconos/ktraini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon18, "")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("iconos/lemke.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon19, "")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("iconos/liliput.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon20, "")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("iconos/lima.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon21, "")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("iconos/mabar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("iconos/maquetren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon23, "")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("iconos/marklin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon24, "")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("iconos/mehano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon25, "")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("iconos/mf-train.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon26, "")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("iconos/NME.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon27, "")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("iconos/omnibus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon28, "")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("iconos/peco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon29, "")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("iconos/piko.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon30, "")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("iconos/rivarossi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon31, "")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("iconos/roco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon32, "")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("iconos/spectrum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon33, "")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("iconos/startrain.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon34, "")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("iconos/sudexpress.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon35, "")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("iconos/thomas&friends.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon36, "")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("iconos/trix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon37, "")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("iconos/viessmann.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon38, "")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("iconos/vitrains.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon39, "")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("iconos/vollmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon40, "")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("iconos/woodland.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon41, "")
        self.linea_separadora3 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora3.setGeometry(QtCore.QRect(0, 230, 1271, 20))
        self.linea_separadora3.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora3.setObjectName("linea_separadora3")
        self.etq_precio = QtWidgets.QLabel(self.centralwidget)
        self.etq_precio.setGeometry(QtCore.QRect(40, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_precio.setFont(font)
        self.etq_precio.setObjectName("etq_precio")
        self.line_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.line_precio.setGeometry(QtCore.QRect(160, 350, 191, 31))
        self.line_precio.setObjectName("line_precio")
        self.etq_stock = QtWidgets.QLabel(self.centralwidget)
        self.etq_stock.setGeometry(QtCore.QRect(40, 420, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_stock.setFont(font)
        self.etq_stock.setObjectName("etq_stock")
        self.line_stock = QtWidgets.QLineEdit(self.centralwidget)
        self.line_stock.setGeometry(QtCore.QRect(160, 420, 191, 31))
        self.line_stock.setObjectName("line_stock")
        self.linea_separadora4 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora4.setGeometry(QtCore.QRect(0, 460, 1291, 20))
        self.linea_separadora4.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora4.setObjectName("linea_separadora4")
        self.linea_separadora1 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora1.setGeometry(QtCore.QRect(10, 30, 511, 20))
        self.linea_separadora1.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora1.setObjectName("linea_separadora1")
        self.linea_separadora2 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora2.setGeometry(QtCore.QRect(820, 30, 481, 20))
        self.linea_separadora2.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora2.setObjectName("linea_separadora2")
        self.etq_fabricante_2 = QtWidgets.QLabel(self.centralwidget)
        self.etq_fabricante_2.setGeometry(QtCore.QRect(40, 580, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_fabricante_2.setFont(font)
        self.etq_fabricante_2.setObjectName("etq_fabricante_2")
        self.edit_descripcion = QtWidgets.QTextEdit(self.centralwidget)
        self.edit_descripcion.setGeometry(QtCore.QRect(160, 490, 391, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_descripcion.setFont(font)
        self.edit_descripcion.setObjectName("edit_descripcion")
        self.boton_imagen = QtWidgets.QPushButton(self.centralwidget)
        self.boton_imagen.setGeometry(QtCore.QRect(780, 590, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_imagen.setFont(font)
        self.boton_imagen.setObjectName("boton_imagen")
        self.linea_separadora5 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora5.setGeometry(QtCore.QRect(0, 760, 1291, 20))
        self.linea_separadora5.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora5.setObjectName("linea_separadora5")
        self.boton_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_registrar.setGeometry(QtCore.QRect(520, 790, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_registrar.setFont(font)
        self.boton_registrar.setObjectName("boton_registrar")
        self.visor_imagen = QtWidgets.QLabel(self.centralwidget)
        self.visor_imagen.setGeometry(QtCore.QRect(930, 490, 300, 250))
        self.visor_imagen.setFrameShape(QtWidgets.QFrame.Box)
        self.visor_imagen.setText("")
        self.visor_imagen.setObjectName("visor_imagen")
        self.etq_euro = QtWidgets.QLabel(self.centralwidget)
        self.etq_euro.setGeometry(QtCore.QRect(370, 360, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.etq_euro.setFont(font)
        self.etq_euro.setObjectName("etq_euro")
        self.caja = QtWidgets.QGroupBox(self.centralwidget)
        self.caja.setGeometry(QtCore.QRect(610, 260, 441, 191))
        self.caja.setObjectName("caja")
        self.radio_analogica = QtWidgets.QRadioButton(self.caja)
        self.radio_analogica.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.radio_analogica.setChecked(True)
        self.radio_analogica.setObjectName("radio_analogica")
        self.radio_digital = QtWidgets.QRadioButton(self.caja)
        self.radio_digital.setGeometry(QtCore.QRect(20, 140, 81, 21))
        self.radio_digital.setObjectName("radio_digital")
        self.check_digital = QtWidgets.QCheckBox(self.caja)
        self.check_digital.setEnabled(False)
        self.check_digital.setGeometry(QtCore.QRect(240, 140, 191, 21))
        self.check_digital.setObjectName("check_digital")
        ventanaRegistro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ventanaRegistro)
        self.statusbar.setObjectName("statusbar")
        ventanaRegistro.setStatusBar(self.statusbar)

        self.retranslateUi(ventanaRegistro)
        QtCore.QMetaObject.connectSlotsByName(ventanaRegistro)

    def retranslateUi(self, ventanaRegistro):
        _translate = QtCore.QCoreApplication.translate
        ventanaRegistro.setWindowTitle(_translate("ventanaRegistro", "Nuevo producto"))
        self.etq_titulo.setText(_translate("ventanaRegistro", "         NUEVO PRODUCTO"))
        self.etq_referencia.setText(_translate("ventanaRegistro", "Referencia: "))
        self.etq_nombre.setText(_translate("ventanaRegistro", "Nombre: "))
        self.etq_tipo.setText(_translate("ventanaRegistro", "Tipo:"))
        self.combo_tipo.setItemText(0, _translate("ventanaRegistro", "Accesorios y decoración"))
        self.combo_tipo.setItemText(1, _translate("ventanaRegistro", "Automotores"))
        self.combo_tipo.setItemText(2, _translate("ventanaRegistro", "Coches"))
        self.combo_tipo.setItemText(3, _translate("ventanaRegistro", "Máquinas"))
        self.combo_tipo.setItemText(4, _translate("ventanaRegistro", "Vagones"))
        self.combo_tipo.setItemText(5, _translate("ventanaRegistro", "Sets"))
        self.combo_tipo.setItemText(6, _translate("ventanaRegistro", "Vías"))
        self.etq_escala.setText(_translate("ventanaRegistro", "Escala: "))
        self.combo_escala.setItemText(0, _translate("ventanaRegistro", "H0"))
        self.combo_escala.setItemText(1, _translate("ventanaRegistro", "N"))
        self.combo_escala.setItemText(2, _translate("ventanaRegistro", "Z"))
        self.etq_fabricante.setText(_translate("ventanaRegistro", "Fabricante:"))
        self.combo_fabricante.setItemText(0, _translate("ventanaRegistro", "Aneste"))
        self.combo_fabricante.setItemText(1, _translate("ventanaRegistro", "Arnold"))
        self.combo_fabricante.setItemText(2, _translate("ventanaRegistro", "Bachmann"))
        self.combo_fabricante.setItemText(3, _translate("ventanaRegistro", "Brawa"))
        self.combo_fabricante.setItemText(4, _translate("ventanaRegistro", "Busch"))
        self.combo_fabricante.setItemText(5, _translate("ventanaRegistro", "Electrotren"))
        self.combo_fabricante.setItemText(6, _translate("ventanaRegistro", "Esu"))
        self.combo_fabricante.setItemText(7, _translate("ventanaRegistro", "Evergreen"))
        self.combo_fabricante.setItemText(8, _translate("ventanaRegistro", "Faller"))
        self.combo_fabricante.setItemText(9, _translate("ventanaRegistro", "Fleischmann"))
        self.combo_fabricante.setItemText(10, _translate("ventanaRegistro", "Graham Farish"))
        self.combo_fabricante.setItemText(11, _translate("ventanaRegistro", "Hobbytrain"))
        self.combo_fabricante.setItemText(12, _translate("ventanaRegistro", "Hornby"))
        self.combo_fabricante.setItemText(13, _translate("ventanaRegistro", "Humbrol"))
        self.combo_fabricante.setItemText(14, _translate("ventanaRegistro", "Ibertren"))
        self.combo_fabricante.setItemText(15, _translate("ventanaRegistro", "Jouef"))
        self.combo_fabricante.setItemText(16, _translate("ventanaRegistro", "Kato"))
        self.combo_fabricante.setItemText(17, _translate("ventanaRegistro", "Kibri"))
        self.combo_fabricante.setItemText(18, _translate("ventanaRegistro", "K*train"))
        self.combo_fabricante.setItemText(19, _translate("ventanaRegistro", "Lemke"))
        self.combo_fabricante.setItemText(20, _translate("ventanaRegistro", "Liliput"))
        self.combo_fabricante.setItemText(21, _translate("ventanaRegistro", "Lima"))
        self.combo_fabricante.setItemText(22, _translate("ventanaRegistro", "Mabar"))
        self.combo_fabricante.setItemText(23, _translate("ventanaRegistro", "Maquetren"))
        self.combo_fabricante.setItemText(24, _translate("ventanaRegistro", "Marklin"))
        self.combo_fabricante.setItemText(25, _translate("ventanaRegistro", "Mehano"))
        self.combo_fabricante.setItemText(26, _translate("ventanaRegistro", "MF-Train"))
        self.combo_fabricante.setItemText(27, _translate("ventanaRegistro", "NME"))
        self.combo_fabricante.setItemText(28, _translate("ventanaRegistro", "Omnibus Models"))
        self.combo_fabricante.setItemText(29, _translate("ventanaRegistro", "Peco"))
        self.combo_fabricante.setItemText(30, _translate("ventanaRegistro", "Piko"))
        self.combo_fabricante.setItemText(31, _translate("ventanaRegistro", "Rivarossi"))
        self.combo_fabricante.setItemText(32, _translate("ventanaRegistro", "Roco"))
        self.combo_fabricante.setItemText(33, _translate("ventanaRegistro", "Spectrum"))
        self.combo_fabricante.setItemText(34, _translate("ventanaRegistro", "Startrain"))
        self.combo_fabricante.setItemText(35, _translate("ventanaRegistro", "Sudexpress"))
        self.combo_fabricante.setItemText(36, _translate("ventanaRegistro", "Thomas & Friends"))
        self.combo_fabricante.setItemText(37, _translate("ventanaRegistro", "Trix"))
        self.combo_fabricante.setItemText(38, _translate("ventanaRegistro", "Viessmann"))
        self.combo_fabricante.setItemText(39, _translate("ventanaRegistro", "Vitrains Models"))
        self.combo_fabricante.setItemText(40, _translate("ventanaRegistro", "Vollmer"))
        self.combo_fabricante.setItemText(41, _translate("ventanaRegistro", "Woodland Scenics"))
        self.etq_precio.setText(_translate("ventanaRegistro", "Precio:"))
        self.etq_stock.setText(_translate("ventanaRegistro", "Stock:"))
        self.etq_fabricante_2.setText(_translate("ventanaRegistro", "Descripción: "))
        self.boton_imagen.setText(_translate("ventanaRegistro", "Cargar imagen"))
        self.boton_registrar.setText(_translate("ventanaRegistro", "REGISTRAR"))
        self.etq_euro.setText(_translate("ventanaRegistro", "€"))
        self.caja.setTitle(_translate("ventanaRegistro", "Tecnología  "))
        self.radio_analogica.setText(_translate("ventanaRegistro", "Analógica"))
        self.radio_digital.setText(_translate("ventanaRegistro", "Digital"))
        self.check_digital.setText(_translate("ventanaRegistro", "con sonido"))
