# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_edicion.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaEdicion(object):
    def setupUi(self, ventanaEdicion):
        ventanaEdicion.setObjectName("ventanaEdicion")
        ventanaEdicion.resize(1109, 888)
        self.centralwidget = QtWidgets.QWidget(ventanaEdicion)
        self.centralwidget.setObjectName("centralwidget")
        self.line_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nombre.setGeometry(QtCore.QRect(550, 130, 521, 31))
        self.line_nombre.setObjectName("line_nombre")
        self.linea_separadora4 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora4.setGeometry(QtCore.QRect(30, 430, 1091, 20))
        self.linea_separadora4.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora4.setObjectName("linea_separadora4")
        self.etq_descripcion = QtWidgets.QLabel(self.centralwidget)
        self.etq_descripcion.setGeometry(QtCore.QRect(50, 470, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_descripcion.setFont(font)
        self.etq_descripcion.setObjectName("etq_descripcion")
        self.etq_precio = QtWidgets.QLabel(self.centralwidget)
        self.etq_precio.setGeometry(QtCore.QRect(460, 335, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_precio.setFont(font)
        self.etq_precio.setObjectName("etq_precio")
        self.etq_stock = QtWidgets.QLabel(self.centralwidget)
        self.etq_stock.setGeometry(QtCore.QRect(820, 335, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_stock.setFont(font)
        self.etq_stock.setObjectName("etq_stock")
        self.etq_euro = QtWidgets.QLabel(self.centralwidget)
        self.etq_euro.setGeometry(QtCore.QRect(740, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.etq_euro.setFont(font)
        self.etq_euro.setObjectName("etq_euro")
        self.etq_referencia = QtWidgets.QLabel(self.centralwidget)
        self.etq_referencia.setGeometry(QtCore.QRect(50, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_referencia.setFont(font)
        self.etq_referencia.setObjectName("etq_referencia")
        self.etq_titulo = QtWidgets.QLabel(self.centralwidget)
        self.etq_titulo.setGeometry(QtCore.QRect(290, 40, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.etq_titulo.setFont(font)
        self.etq_titulo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.etq_titulo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.etq_titulo.setObjectName("etq_titulo")
        self.boton_modificar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_modificar.setGeometry(QtCore.QRect(380, 780, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_modificar.setFont(font)
        self.boton_modificar.setObjectName("boton_modificar")
        self.linea_separadora2 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora2.setGeometry(QtCore.QRect(790, 50, 311, 20))
        self.linea_separadora2.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora2.setObjectName("linea_separadora2")
        self.line_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.line_precio.setGeometry(QtCore.QRect(540, 335, 191, 31))
        self.line_precio.setObjectName("line_precio")
        self.linea_separadora3 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora3.setGeometry(QtCore.QRect(20, 270, 1091, 20))
        self.linea_separadora3.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora3.setObjectName("linea_separadora3")
        self.etq_fabricante = QtWidgets.QLabel(self.centralwidget)
        self.etq_fabricante.setGeometry(QtCore.QRect(50, 345, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_fabricante.setFont(font)
        self.etq_fabricante.setObjectName("etq_fabricante")
        self.combo_escala = QtWidgets.QComboBox(self.centralwidget)
        self.combo_escala.setGeometry(QtCore.QRect(550, 190, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_escala.setFont(font)
        self.combo_escala.setObjectName("combo_escala")
        self.combo_escala.addItem("")
        self.combo_escala.addItem("")
        self.combo_escala.addItem("")
        self.etq_escala = QtWidgets.QLabel(self.centralwidget)
        self.etq_escala.setGeometry(QtCore.QRect(460, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_escala.setFont(font)
        self.etq_escala.setObjectName("etq_escala")
        self.line_referencia = QtWidgets.QLineEdit(self.centralwidget)
        self.line_referencia.setGeometry(QtCore.QRect(140, 130, 191, 31))
        self.line_referencia.setObjectName("line_referencia")
        self.linea_separadora5 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora5.setGeometry(QtCore.QRect(20, 760, 1091, 20))
        self.linea_separadora5.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora5.setObjectName("linea_separadora5")
        self.visor_imagen = QtWidgets.QLabel(self.centralwidget)
        self.visor_imagen.setGeometry(QtCore.QRect(740, 490, 300, 250))
        self.visor_imagen.setFrameShape(QtWidgets.QFrame.Box)
        self.visor_imagen.setText("")
        self.visor_imagen.setObjectName("visor_imagen")
        self.line_stock = QtWidgets.QLineEdit(self.centralwidget)
        self.line_stock.setGeometry(QtCore.QRect(880, 335, 191, 31))
        self.line_stock.setObjectName("line_stock")
        self.edit_descripcion = QtWidgets.QTextEdit(self.centralwidget)
        self.edit_descripcion.setGeometry(QtCore.QRect(50, 510, 391, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_descripcion.setFont(font)
        self.edit_descripcion.setObjectName("edit_descripcion")
        self.linea_separadora1 = QtWidgets.QFrame(self.centralwidget)
        self.linea_separadora1.setGeometry(QtCore.QRect(10, 50, 281, 20))
        self.linea_separadora1.setFrameShape(QtWidgets.QFrame.HLine)
        self.linea_separadora1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linea_separadora1.setObjectName("linea_separadora1")
        self.etq_nombre = QtWidgets.QLabel(self.centralwidget)
        self.etq_nombre.setGeometry(QtCore.QRect(460, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_nombre.setFont(font)
        self.etq_nombre.setObjectName("etq_nombre")
        self.combo_fabricante = QtWidgets.QComboBox(self.centralwidget)
        self.combo_fabricante.setGeometry(QtCore.QRect(140, 325, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_fabricante.setFont(font)
        self.combo_fabricante.setIconSize(QtCore.QSize(48, 48))
        self.combo_fabricante.setObjectName("combo_fabricante")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/aneste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/arnold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iconos/bachmann.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("iconos/brawa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("iconos/busch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("iconos/electrotren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("iconos/esu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("iconos/evergreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("iconos/faller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("iconos/fleischmann.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("iconos/grahamFarish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("iconos/hobbytrain.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("iconos/hornby.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("iconos/humbrol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon13, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("iconos/ibertren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon14, "")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("iconos/jouef.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("iconos/kato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon16, "")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("iconos/kibri.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon17, "")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("iconos/ktraini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon18, "")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("iconos/lemke.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon19, "")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("iconos/liliput.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon20, "")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("iconos/lima.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon21, "")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("iconos/mabar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("iconos/maquetren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon23, "")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("iconos/marklin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon24, "")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("iconos/mehano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon25, "")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("iconos/mf-train.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon26, "")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("iconos/NME.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon27, "")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("iconos/omnibus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon28, "")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("iconos/peco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon29, "")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("iconos/piko.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon30, "")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("iconos/rivarossi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon31, "")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("iconos/roco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon32, "")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("iconos/spectrum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon33, "")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("iconos/startrain.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon34, "")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("iconos/sudexpress.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon35, "")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("iconos/thomas&friends.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon36, "")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("iconos/trix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon37, "")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("iconos/viessmann.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon38, "")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("iconos/vitrains.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon39, "")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("iconos/vollmer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon40, "")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("iconos/woodland.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_fabricante.addItem(icon41, "")
        self.etq_tipo = QtWidgets.QLabel(self.centralwidget)
        self.etq_tipo.setGeometry(QtCore.QRect(50, 195, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etq_tipo.setFont(font)
        self.etq_tipo.setObjectName("etq_tipo")
        self.combo_tipo = QtWidgets.QComboBox(self.centralwidget)
        self.combo_tipo.setGeometry(QtCore.QRect(140, 190, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_tipo.setFont(font)
        self.combo_tipo.setObjectName("combo_tipo")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.boton_imagen = QtWidgets.QPushButton(self.centralwidget)
        self.boton_imagen.setGeometry(QtCore.QRect(570, 620, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boton_imagen.setFont(font)
        self.boton_imagen.setObjectName("boton_imagen")
        ventanaEdicion.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ventanaEdicion)
        self.statusbar.setObjectName("statusbar")
        ventanaEdicion.setStatusBar(self.statusbar)

        self.retranslateUi(ventanaEdicion)
        QtCore.QMetaObject.connectSlotsByName(ventanaEdicion)

    def retranslateUi(self, ventanaEdicion):
        _translate = QtCore.QCoreApplication.translate
        ventanaEdicion.setWindowTitle(_translate("ventanaEdicion", "Editar producto"))
        self.etq_descripcion.setText(_translate("ventanaEdicion", "Descripción: "))
        self.etq_precio.setText(_translate("ventanaEdicion", "Precio:"))
        self.etq_stock.setText(_translate("ventanaEdicion", "Stock:"))
        self.etq_euro.setText(_translate("ventanaEdicion", "€"))
        self.etq_referencia.setText(_translate("ventanaEdicion", "Referencia: "))
        self.etq_titulo.setText(_translate("ventanaEdicion", "       EDICIÓN/ MODIFICACIÓN DEL  PRODUCTO"))
        self.boton_modificar.setText(_translate("ventanaEdicion", "MODIFICAR"))
        self.etq_fabricante.setText(_translate("ventanaEdicion", "Fabricante:"))
        self.combo_escala.setItemText(0, _translate("ventanaEdicion", "H0"))
        self.combo_escala.setItemText(1, _translate("ventanaEdicion", "N"))
        self.combo_escala.setItemText(2, _translate("ventanaEdicion", "Z"))
        self.etq_escala.setText(_translate("ventanaEdicion", "Escala: "))
        self.etq_nombre.setText(_translate("ventanaEdicion", "Nombre: "))
        self.combo_fabricante.setItemText(0, _translate("ventanaEdicion", "Aneste"))
        self.combo_fabricante.setItemText(1, _translate("ventanaEdicion", "Arnold"))
        self.combo_fabricante.setItemText(2, _translate("ventanaEdicion", "Bachmann"))
        self.combo_fabricante.setItemText(3, _translate("ventanaEdicion", "Brawa"))
        self.combo_fabricante.setItemText(4, _translate("ventanaEdicion", "Busch"))
        self.combo_fabricante.setItemText(5, _translate("ventanaEdicion", "Electrotren"))
        self.combo_fabricante.setItemText(6, _translate("ventanaEdicion", "Esu"))
        self.combo_fabricante.setItemText(7, _translate("ventanaEdicion", "Evergreen"))
        self.combo_fabricante.setItemText(8, _translate("ventanaEdicion", "Faller"))
        self.combo_fabricante.setItemText(9, _translate("ventanaEdicion", "Fleischmann"))
        self.combo_fabricante.setItemText(10, _translate("ventanaEdicion", "Graham Farish"))
        self.combo_fabricante.setItemText(11, _translate("ventanaEdicion", "Hobbytrain"))
        self.combo_fabricante.setItemText(12, _translate("ventanaEdicion", "Hornby"))
        self.combo_fabricante.setItemText(13, _translate("ventanaEdicion", "Humbrol"))
        self.combo_fabricante.setItemText(14, _translate("ventanaEdicion", "Ibertren"))
        self.combo_fabricante.setItemText(15, _translate("ventanaEdicion", "Jouef"))
        self.combo_fabricante.setItemText(16, _translate("ventanaEdicion", "Kato"))
        self.combo_fabricante.setItemText(17, _translate("ventanaEdicion", "Kibri"))
        self.combo_fabricante.setItemText(18, _translate("ventanaEdicion", "K*train"))
        self.combo_fabricante.setItemText(19, _translate("ventanaEdicion", "Lemke"))
        self.combo_fabricante.setItemText(20, _translate("ventanaEdicion", "Liliput"))
        self.combo_fabricante.setItemText(21, _translate("ventanaEdicion", "Lima"))
        self.combo_fabricante.setItemText(22, _translate("ventanaEdicion", "Mabar"))
        self.combo_fabricante.setItemText(23, _translate("ventanaEdicion", "Maquetren"))
        self.combo_fabricante.setItemText(24, _translate("ventanaEdicion", "Marklin"))
        self.combo_fabricante.setItemText(25, _translate("ventanaEdicion", "Mehano"))
        self.combo_fabricante.setItemText(26, _translate("ventanaEdicion", "MF-Train"))
        self.combo_fabricante.setItemText(27, _translate("ventanaEdicion", "NME"))
        self.combo_fabricante.setItemText(28, _translate("ventanaEdicion", "Omnibus Models"))
        self.combo_fabricante.setItemText(29, _translate("ventanaEdicion", "Peco"))
        self.combo_fabricante.setItemText(30, _translate("ventanaEdicion", "Piko"))
        self.combo_fabricante.setItemText(31, _translate("ventanaEdicion", "Rivarossi"))
        self.combo_fabricante.setItemText(32, _translate("ventanaEdicion", "Roco"))
        self.combo_fabricante.setItemText(33, _translate("ventanaEdicion", "Spectrum"))
        self.combo_fabricante.setItemText(34, _translate("ventanaEdicion", "Startrain"))
        self.combo_fabricante.setItemText(35, _translate("ventanaEdicion", "Sudexpress"))
        self.combo_fabricante.setItemText(36, _translate("ventanaEdicion", "Thomas & Friends"))
        self.combo_fabricante.setItemText(37, _translate("ventanaEdicion", "Trix"))
        self.combo_fabricante.setItemText(38, _translate("ventanaEdicion", "Viessmann"))
        self.combo_fabricante.setItemText(39, _translate("ventanaEdicion", "Vitrains Models"))
        self.combo_fabricante.setItemText(40, _translate("ventanaEdicion", "Vollmer"))
        self.combo_fabricante.setItemText(41, _translate("ventanaEdicion", "Woodland Scenics"))
        self.etq_tipo.setText(_translate("ventanaEdicion", "Tipo:"))
        self.combo_tipo.setItemText(0, _translate("ventanaEdicion", "Accesorios y decoración"))
        self.combo_tipo.setItemText(1, _translate("ventanaEdicion", "Automotores"))
        self.combo_tipo.setItemText(2, _translate("ventanaEdicion", "Coches"))
        self.combo_tipo.setItemText(3, _translate("ventanaEdicion", "Máquinas"))
        self.combo_tipo.setItemText(4, _translate("ventanaEdicion", "Vagones"))
        self.combo_tipo.setItemText(5, _translate("ventanaEdicion", "Sets"))
        self.combo_tipo.setItemText(6, _translate("ventanaEdicion", "Vías"))
        self.boton_imagen.setText(_translate("ventanaEdicion", "Cargar imagen"))
