# Generated by Django 3.1.2 on 2020-10-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('anyo', models.DateField()),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
    ]
