# Generated by Django 3.1.2 on 2020-10-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0002_auto_20201022_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
