# Generated by Django 3.0.6 on 2020-05-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_auto_20200508_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotografias'),
        ),
    ]
