# Generated by Django 3.0.6 on 2020-05-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_auto_20200509_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anuncios.Usuario'),
            preserve_default=False,
        ),
    ]
