# Generated by Django 3.0.6 on 2020-05-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_anuncio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='email',
        ),
    ]
