# Generated by Django 3.0.6 on 2020-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_remove_anuncio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='nomyapell',
            field=models.CharField(max_length=100, verbose_name='Nombre y apellidos'),
        ),
    ]
