# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_imitador.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 230, 741, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkOpcion4_original = QtWidgets.QCheckBox(self.centralwidget)
        self.checkOpcion4_original.setGeometry(QtCore.QRect(250, 70, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.checkOpcion4_original.setFont(font)
        self.checkOpcion4_original.setObjectName("checkOpcion4_original")
        self.checkOpcion6_original = QtWidgets.QCheckBox(self.centralwidget)
        self.checkOpcion6_original.setGeometry(QtCore.QRect(250, 150, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.checkOpcion6_original.setFont(font)
        self.checkOpcion6_original.setObjectName("checkOpcion6_original")
        self.checkOpcion5_original = QtWidgets.QCheckBox(self.centralwidget)
        self.checkOpcion5_original.setGeometry(QtCore.QRect(250, 110, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.checkOpcion5_original.setFont(font)
        self.checkOpcion5_original.setObjectName("checkOpcion5_original")
        self.editOriginal = QtWidgets.QLineEdit(self.centralwidget)
        self.editOriginal.setGeometry(QtCore.QRect(470, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editOriginal.setFont(font)
        self.editOriginal.setObjectName("editOriginal")
        self.comboOriginal = QtWidgets.QComboBox(self.centralwidget)
        self.comboOriginal.setGeometry(QtCore.QRect(470, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboOriginal.setFont(font)
        self.comboOriginal.setObjectName("comboOriginal")
        self.spinOriginal = QtWidgets.QSpinBox(self.centralwidget)
        self.spinOriginal.setGeometry(QtCore.QRect(470, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinOriginal.setFont(font)
        self.spinOriginal.setObjectName("spinOriginal")
        self.editEspejo = QtWidgets.QLineEdit(self.centralwidget)
        self.editEspejo.setEnabled(False)
        self.editEspejo.setGeometry(QtCore.QRect(470, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editEspejo.setFont(font)
        self.editEspejo.setObjectName("editEspejo")
        self.spinEspejo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinEspejo.setEnabled(False)
        self.spinEspejo.setGeometry(QtCore.QRect(470, 380, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinEspejo.setFont(font)
        self.spinEspejo.setObjectName("spinEspejo")
        self.checkOpcion5_espejo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkOpcion5_espejo.setEnabled(False)
        self.checkOpcion5_espejo.setGeometry(QtCore.QRect(250, 340, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.checkOpcion5_espejo.setFont(font)
        self.checkOpcion5_espejo.setObjectName("checkOpcion5_espejo")
        self.comboEspejo = QtWidgets.QComboBox(self.centralwidget)
        self.comboEspejo.setEnabled(False)
        self.comboEspejo.setGeometry(QtCore.QRect(470, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboEspejo.setFont(font)
        self.comboEspejo.setObjectName("comboEspejo")
        self.checkOpcion4_espejo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkOpcion4_espejo.setEnabled(False)
        self.checkOpcion4_espejo.setGeometry(QtCore.QRect(250, 300, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.checkOpcion4_espejo.setFont(font)
        self.checkOpcion4_espejo.setObjectName("checkOpcion4_espejo")
        self.checkOpcion6_espejo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkOpcion6_espejo.setEnabled(False)
        self.checkOpcion6_espejo.setGeometry(QtCore.QRect(250, 380, 91, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.checkOpcion6_espejo.setFont(font)
        self.checkOpcion6_espejo.setObjectName("checkOpcion6_espejo")
        self.grupoOriginal = QtWidgets.QGroupBox(self.centralwidget)
        self.grupoOriginal.setGeometry(QtCore.QRect(20, 30, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grupoOriginal.setFont(font)
        self.grupoOriginal.setObjectName("grupoOriginal")
        self.radioOpcion1_original = QtWidgets.QRadioButton(self.grupoOriginal)
        self.radioOpcion1_original.setGeometry(QtCore.QRect(20, 40, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioOpcion1_original.setFont(font)
        self.radioOpcion1_original.setObjectName("radioOpcion1_original")
        self.radioOpcion2_original = QtWidgets.QRadioButton(self.grupoOriginal)
        self.radioOpcion2_original.setGeometry(QtCore.QRect(20, 80, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioOpcion2_original.setFont(font)
        self.radioOpcion2_original.setObjectName("radioOpcion2_original")
        self.radioOpcion3_original = QtWidgets.QRadioButton(self.grupoOriginal)
        self.radioOpcion3_original.setGeometry(QtCore.QRect(20, 120, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioOpcion3_original.setFont(font)
        self.radioOpcion3_original.setObjectName("radioOpcion3_original")
        self.grupoEspejo = QtWidgets.QGroupBox(self.centralwidget)
        self.grupoEspejo.setGeometry(QtCore.QRect(20, 260, 191, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grupoEspejo.setFont(font)
        self.grupoEspejo.setObjectName("grupoEspejo")
        self.radioOpcion1_espejo = QtWidgets.QRadioButton(self.grupoEspejo)
        self.radioOpcion1_espejo.setEnabled(False)
        self.radioOpcion1_espejo.setGeometry(QtCore.QRect(20, 40, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioOpcion1_espejo.setFont(font)
        self.radioOpcion1_espejo.setObjectName("radioOpcion1_espejo")
        self.radioOpcion2_espejo = QtWidgets.QRadioButton(self.grupoEspejo)
        self.radioOpcion2_espejo.setEnabled(False)
        self.radioOpcion2_espejo.setGeometry(QtCore.QRect(20, 80, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioOpcion2_espejo.setFont(font)
        self.radioOpcion2_espejo.setObjectName("radioOpcion2_espejo")
        self.radioOpcion3_espejo = QtWidgets.QRadioButton(self.grupoEspejo)
        self.radioOpcion3_espejo.setEnabled(False)
        self.radioOpcion3_espejo.setGeometry(QtCore.QRect(20, 120, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioOpcion3_espejo.setFont(font)
        self.radioOpcion3_espejo.setObjectName("radioOpcion3_espejo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imitador"))
        self.checkOpcion4_original.setText(_translate("MainWindow", "Opción 4"))
        self.checkOpcion6_original.setText(_translate("MainWindow", "Opción 6"))
        self.checkOpcion5_original.setText(_translate("MainWindow", "Opción 5"))
        self.checkOpcion5_espejo.setText(_translate("MainWindow", "Opción 5"))
        self.checkOpcion4_espejo.setText(_translate("MainWindow", "Opción 4"))
        self.checkOpcion6_espejo.setText(_translate("MainWindow", "Opción 6"))
        self.grupoOriginal.setTitle(_translate("MainWindow", "Original"))
        self.radioOpcion1_original.setText(_translate("MainWindow", "Opción 1"))
        self.radioOpcion2_original.setText(_translate("MainWindow", "Opción 2"))
        self.radioOpcion3_original.setText(_translate("MainWindow", "Opción 3"))
        self.grupoEspejo.setTitle(_translate("MainWindow", "Espejo"))
        self.radioOpcion1_espejo.setText(_translate("MainWindow", "Opción 1"))
        self.radioOpcion2_espejo.setText(_translate("MainWindow", "Opción 2"))
        self.radioOpcion3_espejo.setText(_translate("MainWindow", "Opción 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
